blog/urls.py
from django.urls import path
from . import views

app_name="post"

urlpatterns = [
    path('',views.home,name='home'),
    path('post/post_list', views.post_list, name='post_list'),
    path('post/<int:pk>/', views.post_detail, name='post_detail'),
    path('post/new/', views.post_new, name='post_new'),
    path('post/<int:pk>/edit/', views.post_edit, name='post_edit'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('allauth.urls')),
    path('users/',include('users.urls')),
    path('', include('blog.urls')),
    path('ckeditor/',include('ckeditor_uploader.urls')),
  ]

urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .import views

app_name="users"

urlpatterns = [
    path("login",views.users_login,name="login"),
    path("logout",views.users_logout,name="logout"),
    path("signup",views.users_signup,name="signup")
]

blog/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField


class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = RichTextUploadingField()
    created_date = models.DateTimeField(
        default=timezone.now)
    published_date = models.DateTimeField(
        blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):#AbstractUser상속
    #새로운 인자 추가가능
    #예시
    #jobs=models.CharField(max_length=10)
    pass


blog/forms.py
from django import forms

from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'text',)

blog/views.py
from django.shortcuts import render, get_object_or_404,redirect
from django.utils import timezone
from .models import Post
from .forms import PostForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.decorators import login_required

def home(request):
    return render(request, 'blog/home.html')

def post_list(request):
    #페이지 받아오기
    page=request.GET.get('page','1')#page의 값을 get방식으로 가져오는데 없을시 디폴트를 '1'로 지정한다.

    #조회
    posts = Post.objects.order_by('-created_date')
    #posts = Post.objects.all()

    #페이징처리
    paginator=Paginator(posts, 30)
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:#페이지 번호가 없을시
        posts = paginator.page(1)#첫번째페이지 보여줌
    except EmptyPage:#페이지가 비어있을시(페이지 번호 초과시)
        posts = paginator.page(paginator.num_pages)#마지막페이지 보여줌

    #해당 페이지를 index
    index = posts.number

    #마지막 페이지
    max_index = len(paginator.page_range)

    #하단에 보여줄 페이지 범위크기
    page_size=3

    #해당 페이지에서 앞으로 두칸 2보다 작으면 1
    start_index = index - page_size if index > page_size else 1

    #해당 페이지에서 뒤로 두칸
    if index + page_size == max_index:#총 페이지가 3칸 이하일때
        end_index=max_index
    else:#현재 페이지 +2 Max보다 크면 Max로 설정
        end_index = index + page_size if index <= max_index else max_index

    #범위 생성
    # 1' Max
    # 1 Max'
    # 1' 2 3 ... Max
    # 1 2' 3 4 ... Max
    # 1 2 3' 4 5 ... Max
    # 1 ... 2 3 4' 5 6 ... Max
    # 1 ... Max-2 Max-1 Max'
    # 1 ... Max-3 Max-2 Max-1' Max

    #리스트는 0부터 시작함
    page_range = list(paginator.page_range[start_index-1:end_index])

    return render(request, 'blog/post_list.html', {'posts': posts, "page_range":page_range, 'max_index': max_index,'page_size':page_size})


def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    return render(request, 'blog/post_detail.html', {'post': post})

@login_required(login_url="/users/login")
def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('post:post_detail', pk=post.pk)
    else:
        form = PostForm()
    return render(request, 'blog/post_edit.html', {'form': form})

@login_required(login_url="/users/login")
def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('post:post_detail', pk=post.pk)
    else:
        form = PostForm(instance=post)
    return render(request, 'blog/post_edit.html', {'form': form})

users/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate,login,logout
from django.shortcuts import redirect
from .models import User
# Create your views here.
def users_login(request):
    if request.method=='POST':
        username=request.POST["username"]
        password=request.POST["password"]
        #로그인이 필요한 화면에서 왔을때
        beforePage=request.GET.get('next',"post/post_list")
        user=authenticate(username=username,password=password)
        if user is not None:
            login(request,user)
            #이전 화면으로 다시 보내준다
            return redirect(beforePage)
        else:
            print("인증실패")
    return render(request,"users/login.html")


def users_logout(request):
    logout(request)
    return redirect("users:login")


def users_signup(request):
    if request.method=="POST":
        print(request.POST)
        username=request.POST["username"]
        password=request.POST["password"]
        lastname=request.POST["lastname"]
        email=request.POST["email"]

        user=User.objects.create_user(username,email,password)
        user.last_nam=lastname
        user.save()
        return redirect("users:login")

    return render(request,"users/signup.html")

blog/templates/blog/base.html
{% load static %}
<html>
    <head>
        <title>Django blog</title>
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="{% static 'css/styles.css' %}">
        <link rel="stylesheet" href="{% static 'css/blog.css' %}">
        <link rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/all.min.css"
        />
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Langar&display=swap" rel="stylesheet">

    </head>
    <body>
        {% include 'blog/navbar.html' %}
         {% block content %}
         {% endblock %}
        </div>
    </body>
    <script src="{% static 'js/main.js' %}" type="text/javascript" defer></script>

</html>

blog/templates/blog/home.html
{% extends 'blog/base.html' %}
 
{% block content %}

{% endblock %}

blog/templates/blog/navbar.html
<nav class="navbar">
        <div class="navbar__logo">
            <i class="fas fa-apple-alt"></i>
            <a href="/">Strwberry</a>
        </div>
        <div class="navbar__menu">
          <li><a href="">Home</a></li>
          <li><a href="{% url 'post:post_list' %}">blog</a></li>
          <li><a href="">git</a></li>
          <li><a href="">QnA</a></li>
          <li><a href="">Farm</a></li>
        </div>

        <div class="navbar__icons">
            {% if user.is_authenticated %}
            <li><a href=""><i class="fas fa-user"></i></a></li>
            <li><a href="{% url 'users:logout' %}"><i class="fas fa-sign-out-alt"></i></a></li>
            {% else %}
            <li><a href="{% url 'users:login' %}"><i class="fas fa-sign-in-alt"></i></a></li>
            {% endif %}
            <li><i class="fab fa-twitter"></i></li>
            <li><i class="fab fa-facebook"></i></li>
        </div>

        <a href="#" class="navbar__toogleBtn">
            <i class="fas fa-bars"></i>
        </a>

 </nav>

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}
 
{% block content %}
    <div class="main">
        <a href ="{% url 'post:post_edit' pk=post.pk %}"><i class="fas fa-edit"></i></a>
            <div class="date">
                작성일 : {{ post.published_date }}
            </div>
        <a class="btn btn-default" href="{% url 'post:post_edit' pk=post.pk %}"><span class="glyphicon glyphicon-pencil"></span></a>
        <h1>{{ post.title }}</h1>
        {{ post.text|safe}}
        <p>작성자 : {{ post.author }}</p>
        <a href="{% url 'post:post_list'%}">-목록보기-</a>
    </div>

{% endblock %}

blog/templates/blog/post_edit.html
{% extends 'blog/base.html' %}

{% block content %}
    <h1>New post</h1>
    {{form.media}}
    <form method="POST" class="post-form">
        {% csrf_token %}
        {{ form.as_p}}
        <p></p>
        <button type="submit">발행</button>
    </form>
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}

{% block content %}

    <div class="main">
        <!--추가버튼-->
    <div class="postnew">
        <a href="{% url 'post:post_new' %}"><i class="fas fa-plus"></i></a>
    </div>
        <table border="1"  align = "center" class="post_table">
            <colgroup>
                <col width="5%">
                <col width="*%">
                <col width="10%">
                <col width="15%">
                <col width="5%">
                <col width="5%">
            </colgroup>
            <tr class="text-center">
            <th>번호</th>
            <th>제목</th>
            <th>글쓴이</th>
            <th>등록일</th>
            <th>추천</th>
            <th>조회</th>
            {% for post in posts %}
                <tr>
                    <td>{{ post.pk }}</td>
                    <td class="post_table_title"><a class="post-link" href="{% url 'post:post_detail' pk=post.pk %}">{{ post.title }}</a></td>
                    <td>{{ post.author }}</td>
                    <td>{{ post.published_date }}</td>
                    <td>1</td>
                    <td>1</td>
            {% endfor %}
        </table>



    <ul class="paging">
        <!-- 이전페이지 -->
        {% if posts.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ posts.previous_page_number }}"> << </a>
        </li>
        {% endif %}
        <!--이전페이지가 충분하지 않은경우-->
        {% if posts.number > page_size|add:"1" %}
            <li class="page-item"><a class="page-link" href="?page=1">1</a></li>
            <li class="page-item"><span class="page-link" >...</span></li>
        {% endif %}
        <!-- 페이지리스트 -->
        {% for page_number in page_range %}
            {% if page_number == posts.number%}
            <li class="page-item active" aria-current="page">
                <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
            </li>
            {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if posts.number|add:page_size < max_index %}
            <li class="page-item"><span class="page-link" >...</span></li>
            <li class="page-item"><a class="page-link" href="?page={{ max_index }}">{{ max_index }}</a></li>
        {% endif %}

        {% if posts.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ posts.next_page_number }}"> >> </a>
        </li>
        {% endif %}
    </ul>
    </div>
{% endblock %}

users/templates/users/login.html

{% extends 'blog/base.html' %}

{% block content %}

{% if user.is_authenticated %}
    로그인성공!
    {{ user.username}}님 환영합니다.
{% else %}

    <form action="" method="POST">
    {% csrf_token %}
    <input name ="username" type="text">
    <input name ="password" type="password">
    <input type ="submit" value="로그인">
    </form>
    <a href="/accounts/google/login/?process=login">구글로그인</a>
    <a href="/accounts/naver/login/?process=login">네이버로그인</a>


   <a href="{% url 'users:signup' %}">회원가입</a>

{% endif %}

{% endblock %}

users/templates/users/signup.html
{% extends 'blog/base.html' %}
 
{% block content %}

<form action="" method="POST">
    {% csrf_token %}
    <p>아이디</p>
    <input name="username" type="text">
    <p>비밀번호</p>
    <input name="password" type="password">
    <p>이름</p>
    <input name="lastname" type="text">
    <p>이메일</p>
    <input name="email" type="text">
    <p></p>
    <input type="submit" value="회원가입">
</form>

{% endblock %}